import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import './Navbar.css';
import prizeetlogo from "../../assets/prizeet.svg";
import { Icon } from '@iconify/react';
import { NavLink } from 'react-router-dom';
const Navbar = () => {
    const [openMenu, setOpenMenu] = useState(false);
    const toggleMenu = () => setOpenMenu(prev => !prev);
    return (_jsxs("div", { className: 'navbar', children: [_jsx("div", { className: "nav", children: _jsxs("div", { className: 'body', children: [_jsxs("div", { className: "body-section1", children: [_jsx("button", { onClick: toggleMenu, children: _jsx(Icon, { icon: "solar:hamburger-menu-outline", width: "24", height: "24", style: { color: '#111111' } }) }), _jsx("a", { href: "/", children: _jsx("img", { src: prizeetlogo, alt: "" }) }), _jsxs("div", { className: 'hidden-menu-lists', children: [_jsx("a", { href: "https://docs.google.com/forms/d/e/1FAIpQLSdeognUfGQs28lrATNNDfXZUnQSh0MEslbpFC8VGDvt4iFSgg/viewform", children: _jsx("span", { children: "Become a Vendor" }) }), _jsx("a", { href: "about", children: _jsx("span", { children: "About" }) }), _jsx("a", { href: "contact", children: _jsx("span", { children: "Contact" }) })] })] }), _jsx("div", { className: "body-section2", children: _jsxs("div", { className: "body", children: [_jsx("button", { className: 'button1', children: _jsx(Icon, { icon: "solar:magnifer-outline", className: 'span1' }) }), _jsxs("button", { className: 'button2', children: [" ", _jsx(Icon, { icon: "solar:user-outline", className: 'span2' })] }), _jsxs("button", { className: 'button3', children: [_jsx("span", { className: 'span3', children: "0" }), _jsx("span", { className: 'span3-2', children: _jsx(Icon, { icon: "solar:cart-large-minimalistic-outline", className: "cart-icon", width: "24", height: "24" }) })] })] }) })] }) }), _jsx("div", { className: `nav-overlay ${openMenu ? "open" : "close"}`, children: _jsxs("ul", { className: "nav-links", children: [_jsx("li", { children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive ? "active-link" : "", children: "Home" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive ? "active-link" : "", children: "About" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive ? "active-link" : "", children: "Contact" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive ? "active-link" : "", children: "Products" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive ? "active-link" : "", children: "Become a Vendor" }) })] }) })] }));
};
export default Navbar;
